---
- name: mise a jour du systeme
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: install MySQL
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - python-mysqldb
  notify: start mysql

- name: port de ouvert sur 3306
  iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: 3306
    jump: ACCEPT

- name: mysql bind-address configuration
  lineinfile:
    dest: /etc/mysql/my.cnf
    regexp: '^(bind-address).*$'
    line: '\1=0.0.0.0'
    backrefs: yes

- name: wordpress BDD
  mysql_db:
    db: "wordpress"
    state: present

- name: wordpress user for {{groups.WEBserver | to_json | replace('"','') | replace('[','') | replace(']','')}}
  mysql_user:
    name: "wordpress"
    password: "P@ssw0rd"
    host: "{{groups.WEBserver | to_json | replace('\"','') | replace('[','') | replace(']','')}}"
    priv: 'wordpress.*:ALL'
    state: present
  notify: restart mysql
