- name: Install BDD
  hosts: BDD
  roles:
    - role: BDD
      MySQL_password: "P@ssw0rd"
      become: yes

- name: Install WEBserver
  hosts: WEBserver
  become: yes
  roles:
    - role: WEBserver
    - role: Wordpress
